// <auto-generated />
using System;
using LogLibrary.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogLibrary.Migrations
{
    [DbContext(typeof(LogDbContext))]
    [Migration("20260525044021_RemoveIdFromCiscoModel")]
    partial class RemoveIdFromCiscoModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogAPI.Classes.DB_Data.CiscoDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceName")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("LogAPI.Classes.DB_Data.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceName");

                    b.HasIndex("DeviceName", "Date")
                        .HasDatabaseName("IX_DeviceName_Date");

                    b.HasIndex("DeviceName", "Date", "Command")
                        .IsUnique();

                    b.ToTable("RawLogs");
                });

            modelBuilder.Entity("LogAPI.Classes.DB_Data.LogSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceName", "Date", "Command")
                        .IsUnique();

                    b.ToTable("LogSummaries");
                });

            modelBuilder.Entity("LogLibrary.Classes.DB_Data.CiscoModel", b =>
                {
                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.HasKey("ModelName");

                    b.ToTable("CiscoModels");
                });

            modelBuilder.Entity("LogLibrary.Classes.DB_Data.DeviceToModel", b =>
                {
                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DeviceName");

                    b.HasIndex("ModelName");

                    b.ToTable("DeviceToModelMappings");
                });

            modelBuilder.Entity("LogLibrary.Classes.DB_Data.ModelCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ModelName", "CommandText")
                        .IsUnique();

                    b.ToTable("ModelCommands");
                });

            modelBuilder.Entity("LogAPI.Classes.DB_Data.LogEntry", b =>
                {
                    b.HasOne("LogAPI.Classes.DB_Data.CiscoDevice", null)
                        .WithMany()
                        .HasForeignKey("DeviceName")
                        .HasPrincipalKey("DeviceName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogLibrary.Classes.DB_Data.DeviceToModel", b =>
                {
                    b.HasOne("LogAPI.Classes.DB_Data.CiscoDevice", null)
                        .WithOne()
                        .HasForeignKey("LogLibrary.Classes.DB_Data.DeviceToModel", "DeviceName")
                        .HasPrincipalKey("LogAPI.Classes.DB_Data.CiscoDevice", "DeviceName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogLibrary.Classes.DB_Data.CiscoModel", null)
                        .WithMany()
                        .HasForeignKey("ModelName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogLibrary.Classes.DB_Data.ModelCommand", b =>
                {
                    b.HasOne("LogLibrary.Classes.DB_Data.CiscoModel", null)
                        .WithMany()
                        .HasForeignKey("ModelName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
